version: '3.8'

services:
  laravel_app:
    image: ruang_organisasi-app
    ports:
      - "8080:8000"
      - "9000:9000"
    networks:
      - app-network
    depends_on:
      - laravel_db

  laravel_db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ruang_organisasi_dbdata:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  ruang_organisasi_dbdata:
